// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'externalLink': string;
  'imdbId': string;
  'title': string;
  'tmdbId': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
